name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build_android:
    name: Build Android AAB
    type: build
    params:
      platform: android
      profile: production
